default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: company_analysis_development

test:
  <<: *default
  database: company_analysis_test

production:
  <<: *default
  database: company_analysis_production
